// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-zvaMrq8tbjV926l0X8QAZnfUG44zJco',
    appId: '1:109732420761:web:7f94eeccc6424cb7336c08',
    messagingSenderId: '109732420761',
    projectId: 'studie-68ed5',
    authDomain: 'studie-68ed5.firebaseapp.com',
    storageBucket: 'studie-68ed5.firebasestorage.app',
    measurementId: 'G-7D6GG3DC08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbAprjMj_rVGFScY00RhyXTw-uXeLYvJE',
    appId: '1:109732420761:android:b08ca17415775d40336c08',
    messagingSenderId: '109732420761',
    projectId: 'studie-68ed5',
    storageBucket: 'studie-68ed5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0pp5uxjrScJXoJeSI7rwOrFU0g9JcBDc',
    appId: '1:109732420761:ios:3132671d3261d089336c08',
    messagingSenderId: '109732420761',
    projectId: 'studie-68ed5',
    storageBucket: 'studie-68ed5.firebasestorage.app',
    iosClientId: '109732420761-jh2kehv8doj53i2cm56ta15tr7s0mdj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0pp5uxjrScJXoJeSI7rwOrFU0g9JcBDc',
    appId: '1:109732420761:ios:3132671d3261d089336c08',
    messagingSenderId: '109732420761',
    projectId: 'studie-68ed5',
    storageBucket: 'studie-68ed5.firebasestorage.app',
    iosClientId: '109732420761-jh2kehv8doj53i2cm56ta15tr7s0mdj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-zvaMrq8tbjV926l0X8QAZnfUG44zJco',
    appId: '1:109732420761:web:49912c1ef8f8c294336c08',
    messagingSenderId: '109732420761',
    projectId: 'studie-68ed5',
    authDomain: 'studie-68ed5.firebaseapp.com',
    storageBucket: 'studie-68ed5.firebasestorage.app',
    measurementId: 'G-70XGZJ6PJ2',
  );

}