// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/features/view/home_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i9;

import 'package:app/features/data/repository/tasks_repository_impl.dart' as _i5;
import 'package:app/features/data/source/database/database.dart' as _i2;
import 'package:app/features/domain/entities/task.dart' as _i6;
import 'package:app/utils/helpers/database_instance.dart' as _i4;
import 'package:get/get.dart' as _i3;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppDataBase_0 extends _i1.SmartFake implements _i2.AppDataBase {
  _FakeAppDataBase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxString_1 extends _i1.SmartFake implements _i3.RxString {
  _FakeRxString_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxList_2<E> extends _i1.SmartFake implements _i3.RxList<E> {
  _FakeRxList_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_3<T> extends _i1.SmartFake
    implements _i3.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseInstance].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseInstance extends _i1.Mock implements _i4.DatabaseInstance {
  @override
  _i2.AppDataBase get getdatabase =>
      (super.noSuchMethod(
            Invocation.getter(#getdatabase),
            returnValue: _FakeAppDataBase_0(
              this,
              Invocation.getter(#getdatabase),
            ),
            returnValueForMissingStub: _FakeAppDataBase_0(
              this,
              Invocation.getter(#getdatabase),
            ),
          )
          as _i2.AppDataBase);

  @override
  set database(_i2.AppDataBase? value) => super.noSuchMethod(
    Invocation.setter(#database, value),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TaskRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepositoryImpl extends _i1.Mock
    implements _i5.TaskRepositoryImpl {
  @override
  _i2.AppDataBase get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _FakeAppDataBase_0(this, Invocation.getter(#database)),
            returnValueForMissingStub: _FakeAppDataBase_0(
              this,
              Invocation.getter(#database),
            ),
          )
          as _i2.AppDataBase);

  @override
  _i3.RxString get nome =>
      (super.noSuchMethod(
            Invocation.getter(#nome),
            returnValue: _FakeRxString_1(this, Invocation.getter(#nome)),
            returnValueForMissingStub: _FakeRxString_1(
              this,
              Invocation.getter(#nome),
            ),
          )
          as _i3.RxString);

  @override
  _i3.RxList<_i6.Task> get tasks =>
      (super.noSuchMethod(
            Invocation.getter(#tasks),
            returnValue: _FakeRxList_2<_i6.Task>(
              this,
              Invocation.getter(#tasks),
            ),
            returnValueForMissingStub: _FakeRxList_2<_i6.Task>(
              this,
              Invocation.getter(#tasks),
            ),
          )
          as _i3.RxList<_i6.Task>);

  @override
  set nome(_i3.RxString? value) => super.noSuchMethod(
    Invocation.setter(#nome, value),
    returnValueForMissingStub: null,
  );

  @override
  set tasks(_i3.RxList<_i6.Task>? value) => super.noSuchMethod(
    Invocation.setter(#tasks, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_3<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_3<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_3<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_3<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(
            Invocation.getter(#listeners),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i7.Future<void> initializeController({
    required String? nome,
    dynamic required,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initializeController, [], {
              #nome: nome,
              #required: required,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> checkIfHasTaskThisHour(_i6.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#checkIfHasTaskThisHour, [task]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<int> createTask({required _i6.Task? task}) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [], {#task: task}),
            returnValue: _i7.Future<int>.value(0),
            returnValueForMissingStub: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> deleteTask({required _i6.Task? task}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [], {#task: task}),
            returnValue: _i7.Future<int>.value(0),
            returnValueForMissingStub: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<List<_i6.Task>> getTasksByWeekDay({required String? weekdays}) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByWeekDay, [], {#weekdays: weekdays}),
            returnValue: _i7.Future<List<_i6.Task>>.value(<_i6.Task>[]),
            returnValueForMissingStub: _i7.Future<List<_i6.Task>>.value(
              <_i6.Task>[],
            ),
          )
          as _i7.Future<List<_i6.Task>>);

  @override
  _i7.Future<bool> setTaskChecked({required _i6.Task? task}) =>
      (super.noSuchMethod(
            Invocation.method(#setTaskChecked, [], {#task: task}),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<_i6.Task?> updateTask({required _i6.Task? task}) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [], {#task: task}),
            returnValue: _i7.Future<_i6.Task?>.value(),
            returnValueForMissingStub: _i7.Future<_i6.Task?>.value(),
          )
          as _i7.Future<_i6.Task?>);

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Disposer addListener(_i8.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i8.Disposer);

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i9.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Disposer addListenerId(Object? key, _i8.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i8.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}
